version: '3'
  
services:

  app:
    image: 1056699051/louispythonapp
    ports:
      - 80:8000
    depends_on:
      - mysql-security
    environment:
      MYSQL_SECURITY_ENV_HOST: mysql-security
      MYSQL_SECURITY_ENV_MYSQL_DATABASE: demo
      MYSQL_SECURITY_PORT_3306_TCP_PORT: 3306
      MYSQL_SECURITY_ENV_MYSQL_ROOT_PASSWORD: root
    networks:
      - my-bridge

  mysql-security:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    volumes:
      - mysql-security:/var/lib/mysql
    networks:
      - my-bridge

volumes:
  mysql-security:

networks:
  my-bridge:
    driver: bridge
